### ISSUE TITLE
test image dataset link is broken

### ISSUE THREAD

**Issue by ahenkvural** [leftthomas/SRGAN#66] opened 2020-03-23 20:59 UTC
I train the network with DIV2K set, after that I want to test an image but  the result is not good enough like  as an SR image. Therefore, I decided to use your benchmark dataset but it is broken. Could you please refresh the dataset link? Thanks.

**Comment by leftthomas** [comment] 2020-03-24 09:04
@ahenkvural 
Duplicate of #45

**Closed by leftthomas** 2020-03-24 09:04 UTC
