### ISSUE TITLE
About the form of the loss function

### ISSUE THREAD

**Issue by njuhang** [leftthomas/SRGAN#102] opened 2021-04-12 05:06 UTC
why choose 1-D(x).mean+D(Gz)).mean() as loss function of Discriminator, rather than BCELoss? And the form of Generator loss function is different from the paper. Are the pictures and PSNR data shown here trained by this code?  Why is my training result close to the interpolation result?

**Comment by leftthomas** [comment] 2021-04-12 16:39
@njuhang
Duplicate of #101

**Closed by leftthomas** 2021-04-12 16:39 UTC
