### ISSUE TITLE
about discriminator loss

### ISSUE THREAD

**Issue by JeromeYHJ** [leftthomas/SRGAN#69] opened 2020-04-28 12:42 UTC
why discriminator loss set:
d_loss = 1 - real_out + fake_out
is it same as the paper?
why not use torch.nn.BCELoss() to calculate Cross Entropy?
anyway thx

**Comment by leftthomas** [comment] 2020-04-29 13:19
@JeromeYHJ 
Duplicate of #46

**Closed by leftthomas** 2020-04-29 13:20 UTC
