### ISSUE TITLE
 RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by qiqiing** [leftthomas/SRGAN#88] opened 2020-11-28 04:01 UTC
hello,When I ran train.py, I got an error: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 1024, 1, 1]] is at version 2;I looked for some solutions on the Internet, but I still couldn't solve the mistake.Do you know what the reason is and how to solve it?

**Comment by MattyCZ** [comment] 2020-11-29 10:49
I had the same problem, fixed by using torch==1.4.0 and torchvision==0.5 . Not really long term fix

**Comment by leftthomas** [comment] 2020-11-30 05:20
@qiqiing 
Duplicate of #84

**Closed by leftthomas** 2020-11-30 05:20 UTC
